image: gitpod/workspace-go
tasks:
# Retrieve our go dependencies. Also inject several vscode settings that are specifically helpful to a GitPod environment and not needed when opening the repo locally.
# The reason the settings are copied to a temp file and then moved is that applying the jq string directly to settings.json results in a blank file.
  - init: |
      go get
  - name: Start acceptance Test Environment
    command: make testacc-up
    openMode: split-right
# Port 8080 is used for acceptance testing, and we don't need to open it when the container comes up
ports:
  - port: 8080
    onOpen: ignore
vscode:
    extensions:
        - golang.Go
        - hashicorp.terraform